#!/usr/bin/env bash
BUILD_DIR="bld/"

if [ -d "$BUILD_DIR" ]; then
    echo "Re-making build dir at $BUILD_DIR"
    rm -rf "$BUILD_DIR"
fi
mkdir "$BUILD_DIR"

cd "$BUILD_DIR"
#CC=gcc-5 CXX=g++-5 cmake ..
CC=gcc CXX=g++ cmake ..
make

cd ..
